### ISSUE TITLE
Unable to enter next quest (Valkyrie Save system Bug)

### ISSUE THREAD

**Issue by Astner** [DelphiDie/TheShadowRune#2] opened 2018-06-06 14:49 UTC
After completing the "The Cardinal’s Plight" mission I got to the map screen and is stuck there. I can see the other missions and trigger travel events but when the party arrives there is the sound effect but misson does not start. 
Restarting/reloading to beginning of map phase (earliest save I have got unfortunately) does nothing. Running on Mac.

**Comment by DelphiDie** [comment] 2018-06-07 16:59
Hello Astner,

I'm sorry to hear you have a problem. Would it be possible for you to attach a save file? I fear I won't be able to diagnose this without one.

Thanks in advance.

**Comment by Aaronel-1** [comment] 2018-06-12 17:32
Also having the same problem once finished First Blood and traveling to A Fat Goblin - the 3 road events play out properly and I hear the mission sound effect, but the mission does not load and I stay on the map screen.

[Save.zip](https://github.com/DelphiDie/TheShadowRune/files/2095194/Save.zip)

Windows 10 64bit (up to date)

Really love what you guys have done here!

**Comment by DelphiDie** [comment] 2018-06-13 10:00
Thanks for providing the save file Aaronel. I was able to run some tests, and I can reproduce the bug.

Unfortunately, it seems to be a problem of Valkyrie's integrated save system. Once I save and load a game, the bug occurs whenever the game is supposed to change to a new quest or to the campaign phase.

I will ask Bruce to look at this. My guess would be, that the save system was created before there was the ability to trigger new quests from within quests to create a campaign, and that it somehow doesn't take this into account.

Sadly this means, that saving and loading seems to be impossible at the moment, which of course is really inconvenient for the scope of this project. I hope this can be fixed as soon as possible and I'm very sorry.

I will keep this issue open and post any news about it here.

**Comment by Aaronel-1** [comment] 2018-06-13 17:02
Thank you for the quick response DelphiDie ... will keep my fingers crossed that there will be a solution to this problem.  
Again thank you for all the work you guys have done here ...

**Comment by DelphiDie** [comment] 2018-09-02 12:38
Someone is looking into the problem. We do not yet know whether it is easyily fixable, but we should know more soon.

**Comment by DelphiDie** [comment] 2018-09-04 09:05
I have good news to report: Thanks to @BenRQ the problem with saving and loading is finally fixed.

I had to rework the campaign a bit, but it now works flawlessly with a new beta release.

As soon as there is a new official Valkyrie version I will push the new release that fixes the problem.

Sorry it took so long to get this done. I'll keep the issue open until the new release is out.

**Comment by Aaronel-1** [comment] 2018-09-04 10:29
Excellent news!

**Comment by DelphiDie** [comment] 2018-09-17 10:58
I just released the next Valkyrie update, which fixes the save/load issues in combination with the Valkyrie Brynhildr release.

You can find it over here: https://github.com/BenRQ/valkyrie/releases

Thanks for your patience. I will close the issue for now, but do not hesitate to reopen it or create a new one if you encounter any problems.

**Comment by MrTantum** [comment] 2019-06-09 14:59
Could you please update to the newest valkyrie version and try again? For which quests does this error occur?

**Comment by booleanBoy** [comment] 2019-06-09 15:20
Coincidentally I did update (install new version over the top of old version) yesterday. I loaded up a fresh campaign, played a couple of quests, saved, quit, start valkyrie again, loaded the save, clicked on a quest on the map, got the travel events, then nothing.
It happens for any quest on the map, ones that we've played after the initial quest so we know they work, its just always after saving, quitting and loading again that they all fail to load.

**Comment by MrTantum** [comment] 2019-06-09 15:25
Are you plaing on pc or android?

**Comment by booleanBoy** [comment] 2019-06-09 22:43
PC, Windows 10.

I followed your steps and had the same problem. I uninstalled, deleted the app data folder, redownloaded, reinstalled, redownloaded the campaign and had the same experience. 

Whenever I reload the app and try to select a new quest, I get travel events and the drums sound effects then nothing. When I then click any quest I get no travel events, just the question of whether I want to do the quest, then the drums sound effect, with no advancement.

This occurs on my desktop and my laptop, both Win10. I think it also occurs on my friends Win10 machine as well.

Is there anything I can do to help debug this?

**Comment by MrTantum** [comment] 2019-06-10 12:02
Can you please upload your savegame from "AppData\Roaming\Valkyrie\D2E\Save"

**Comment by booleanBoy** [comment] 2019-06-12 07:44
[Save.zip](https://github.com/DelphiDie/TheShadowRune/files/3280158/Save.zip)

Here you go. Good luck!

**Comment by DelphiDie** [comment] 2019-06-17 13:51
Hello @booleanBoy 

I took a look at the problem, and it seems to be tricky. At first I couldn't reproduce it with one of my own saves, but after some testing I was.

One crucial part of reproducing the error is closing and restarting Valkyrie before reloading the save game. Unfortunately there is nothing I can do about it personally, but I will create an issue on the Valkyrie bugtracker.

Regards,
Delphi

**Comment by booleanBoy** [comment] 2019-06-17 16:56
Thanks for taking the time to look into it, and of course the work all of you do on the app and the campaign!

**Comment by DelphiDie** [comment] 2019-08-12 10:14
The problem has been fixed in Valkyrie 2.4.0.1. You can download it over here: https://github.com/NPBruce/valkyrie/releases/latest

**Closed by DelphiDie** 2019-08-12 10:14 UTC
Labels: bug
